---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  vars:
    keycloak_admin_password: "remembertochangeme"
    keycloak_rhsso_enable: True
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.keycloak
  roles:
    - middleware_automation.redhat_csp_download.redhat_csp_download
    - middleware_automation.keycloak.keycloak
